version: '3'

services:
  dj_db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  dj_broker:
    container_name: dj_broker
    image: rabbitmq:latest
    ports:
      - "5673:5673"
  dj_worker:
    container_name: dj_worker
    build: .
    volumes:
      - .:/code
    command: "celery worker --app=djangoproject --concurrency=1 --loglevel=debug"
    depends_on:
      - dj_broker
  django_boilerplate:
    container_name: django_boilerplate
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - dj_db
